# Data Cleaning — Synthetic Gender Sensitization Survey
## ⚠️ SYNTHETIC DATA DISCLAIMER

**This entire notebook operates on `synthetic_survey.csv`, a 100% artificially
generated dataset.**

- No real survey respondents are represented in this file.
- The data was produced by a Python script (`generate_dataset.py`) using
  random sampling, loosely targeting the *aggregate* percentages published
  in a dissertation on gender sensitization in Kanpur — but **no real
  individual-level responses were ever used**.
- Some relationships between variables (e.g., education vs. awareness) were
  **deliberately and artificially injected** into the data generation process
  purely to make the dataset useful for analytics/ML demonstrations.
- **Do not** interpret any statistic, chart, or "finding" in this notebook as
  evidence about real attitudes, real people, or the real world. This is a
  technical demonstration only.

## 1. Import Libraries
We import the core libraries used throughout this notebook:
- `pandas` for tabular data handling
- `numpy` for numerical operations
- `matplotlib.pyplot` for static plots
- `plotly.express` / `plotly.graph_objects` for interactive plots

In [1]:
# Import core data-handling libraries
import pandas as pd            # for reading/manipulating tabular data
import numpy as np             # for numerical operations (e.g., NaN handling)

# Import plotting libraries
import matplotlib.pyplot as plt    # static, publication-style plots
import plotly.express as px        # quick interactive plots
import plotly.graph_objects as go  # fine-grained interactive plots

# Set a clean, professional style for matplotlib charts
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (9, 5)
plt.rcParams['axes.titlesize'] = 13
plt.rcParams['axes.titleweight'] = 'bold'

# Display all dataframe columns when printing (helps inspect wide tables)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 150)

print("Libraries imported successfully.")

Libraries imported successfully.

## 2. Load the Synthetic Dataset
We load `synthetic_survey.csv` directly into a pandas DataFrame.

**Reminder: every row in this file is synthetic / artificially generated.**

In [2]:
# Load the synthetic survey CSV into a pandas DataFrame
df = pd.read_csv("synthetic_survey.csv")

# Quick confirmation of dataset size (rows, columns)
print(f"Dataset shape: {df.shape[0]} rows x {df.shape[1]} columns")
print("\nReminder: this is a SYNTHETIC dataset. No real respondents are included.")

# Preview the first 5 rows to get a feel for the data
df.head()

Dataset shape: 1000 rows x 28 columns

Reminder: this is a SYNTHETIC dataset. No real respondents are included.

,respondent_id,age_group,gender,education,heard_term_gender_sensitization,gender_is_binary_or_nonbinary,received_gender_training,support_school_curriculum,support_workplace_training,sensitization_helps_relationships,stereotype_men_rational_women_emotional,stereotype_women_bad_drivers,view_okay_for_men_to_cry,stereotype_men_strong_women_weak,stereotype_women_better_housekeepers,stereotype_gentle_men_less_masculine,childcare_only_mother_responsibility,woman_home_man_provider_role,chores_divided_equally_if_both_work,support_equal_pay,support_gender_diversity_quotas,discrimination_observed_nearby,support_gender_neutral_language,encourage_girls_nontraditional_careers,man_should_have_final_say_home,woman_should_not_tolerate_violence,sexist_jokes_okay,sensitization_reduces_gbv
0,R0001,18-25,Female,Bachelor's degree,Yes,Non-binary,No,Maybe,"Yes, definitely",Yes,Agree,Disagree,Agree,Agree,Agree,Disagree,No,Yes,"Yes, definitely",Yes,Yes,No,Maybe,Yes,No,Maybe,No,Yes
1,R0002,18-25,Male,Bachelor's degree,No,Non-binary,No,"No, not required","Yes, definitely",Yes,Disagree,Disagree,Agree,Disagree,Disagree,Agree,Yes,Yes,"Yes, definitely",Yes,Yes,Yes,Yes,Yes,No,No,No,Maybe
2,R0003,18-25,Female,Bachelor's degree,Yes,Binary,Yes,"No, not required","Yes, definitely",Yes,Disagree,Neutral,Agree,Disagree,Agree,Disagree,No,Yes,"No, the woman should manage both",Yes,Yes,No,Yes,Maybe,No,No,No,Yes
3,R0004,18-25,Male,Master's degree,Yes,Binary,No,"Yes, definitely","Yes, definitely",Yes,Agree,Disagree,Agree,Disagree,Agree,Disagree,No,No,"No, the woman should manage both",Yes,Yes,No,Yes,Yes,No,No,No,Yes
4,R0005,26-35,Male,Master's degree,Yes,Non-binary,Yes,Maybe,Maybe,Yes,Disagree,Disagree,Agree,Disagree,Disagree,Disagree,No,Yes,"Yes, definitely",Yes,Unsure,Unsure,Maybe,Yes,No,Yes,Maybe,Yes

## 3. Initial Structural Inspection
Before cleaning, we inspect data types, column names, and basic info to understand what we're working with.

In [3]:
# List all column names — useful for spotting typos or unexpected columns
print("Column names:")
for col in df.columns:
    print(f"  - {col}")

Column names:
  - respondent_id
  - age_group
  - gender
  - education
  - heard_term_gender_sensitization
  - gender_is_binary_or_nonbinary
  - received_gender_training
  - support_school_curriculum
  - support_workplace_training
  - sensitization_helps_relationships
  - stereotype_men_rational_women_emotional
  - stereotype_women_bad_drivers
  - view_okay_for_men_to_cry
  - stereotype_men_strong_women_weak
  - stereotype_women_better_housekeepers
  - stereotype_gentle_men_less_masculine
  - childcare_only_mother_responsibility
  - woman_home_man_provider_role
  - chores_divided_equally_if_both_work
  - support_equal_pay
  - support_gender_diversity_quotas
  - discrimination_observed_nearby
  - support_gender_neutral_language
  - encourage_girls_nontraditional_careers
  - man_should_have_final_say_home
  - woman_should_not_tolerate_violence
  - sexist_jokes_okay
  - sensitization_reduces_gbv

In [4]:
# df.info() gives us: data type per column, non-null counts, and memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   respondent_id                            1000 non-null   str
 1   age_group                                1000 non-null   str
 2   gender                                   1000 non-null   str
 3   education                                1000 non-null   str
 4   heard_term_gender_sensitization          1000 non-null   str
 5   gender_is_binary_or_nonbinary            1000 non-null   str
 6   received_gender_training                 1000 non-null   str
 7   support_school_curriculum                1000 non-null   str
 8   support_workplace_training               1000 non-null   str
 9   sensitization_helps_relationships        1000 non-null   str
 10  stereotype_men_rational_women_emotional  1000 non-null   str
 11  stereotype_women_bad_drivers             1000 non-null   str
 12  view_okay_for_men_to_cry                 1000 non-null   str
 13  stereotype_men_strong_women_weak         1000 non-null   str
 14  stereotype_women_better_housekeepers     1000 non-null   str
 15  stereotype_gentle_men_less_masculine     1000 non-null   str
 16  childcare_only_mother_responsibility     1000 non-null   str
 17  woman_home_man_provider_role             1000 non-null   str
 18  chores_divided_equally_if_both_work      1000 non-null   str
 19  support_equal_pay                        1000 non-null   str
 20  support_gender_diversity_quotas          1000 non-null   str
 21  discrimination_observed_nearby           1000 non-null   str
 22  support_gender_neutral_language          1000 non-null   str
 23  encourage_girls_nontraditional_careers   1000 non-null   str
 24  man_should_have_final_say_home           1000 non-null   str
 25  woman_should_not_tolerate_violence       1000 non-null   str
 26  sexist_jokes_okay                        1000 non-null   str
 27  sensitization_reduces_gbv                1000 non-null   str
dtypes: str(28)
memory usage: 218.9 KB

## 4. Check for Missing Values
We check each column for missing (`NaN`) values. Since this is a synthetic dataset generated by a script, we expect very few or no missing values — but we check systematically anyway, as we would for any real-world dataset.

In [5]:
# Count missing values per column
missing_counts = df.isnull().sum()

# Convert to a tidy DataFrame for easy viewing, sorted descending
missing_summary = (
    missing_counts[missing_counts > 0]
    .sort_values(ascending=False)
    .to_frame(name="missing_count")
)
missing_summary["missing_pct"] = (missing_summary["missing_count"] / len(df) * 100).round(2)

if missing_summary.empty:
    print("No missing values found in any column.")
else:
    print("Columns with missing values:")
    display(missing_summary)

No missing values found in any column.

## 5. Check for Duplicate Rows
We check whether any respondent rows are exact duplicates, and whether `respondent_id` values are unique (they should be, since each synthetic respondent was assigned a unique ID during generation).

In [6]:
# Check for fully duplicated rows (all columns identical)
n_duplicate_rows = df.duplicated().sum()
print(f"Fully duplicated rows: {n_duplicate_rows}")

# Check that respondent_id is unique (it should act as a primary key)
n_duplicate_ids = df['respondent_id'].duplicated().sum()
print(f"Duplicate respondent_id values: {n_duplicate_ids}")

if n_duplicate_rows == 0 and n_duplicate_ids == 0:
    print("\nNo duplicate rows or IDs detected — dataset integrity looks good.")

Fully duplicated rows: 0
Duplicate respondent_id values: 0

No duplicate rows or IDs detected — dataset integrity looks good.

## 6. Validate Categorical Values
For each categorical column, we list the unique values present. This helps catch inconsistent labels (e.g., `'Yes'` vs `'yes'` vs `'Y'`) that would need standardizing in a real-world cleaning pipeline.

In [7]:
# Identify all columns except the unique ID column as categorical
categorical_cols = [c for c in df.columns if c != 'respondent_id']

# Print unique values for each categorical column
for col in categorical_cols:
    uniques = df[col].unique()
    print(f"{col}: {sorted(uniques.tolist())}")

age_group: ['18-25', '26-35', 'Less than 18', 'More than 35']
gender: ['Female', 'Male']
education: ["Bachelor's degree", 'High school or equivalent', "Master's degree"]
heard_term_gender_sensitization: ['No', 'Yes']
gender_is_binary_or_nonbinary: ['Binary', 'Non-binary', 'Unsure']
received_gender_training: ['No', 'Yes']
support_school_curriculum: ['Maybe', 'No, not required', 'Yes, definitely']
support_workplace_training: ['Maybe', 'No, not required', 'Yes, definitely']
sensitization_helps_relationships: ['Maybe', 'No', 'Yes']
stereotype_men_rational_women_emotional: ['Agree', 'Disagree', 'Neutral']
stereotype_women_bad_drivers: ['Agree', 'Disagree', 'Neutral']
view_okay_for_men_to_cry: ['Agree', 'Disagree', 'Neutral']
stereotype_men_strong_women_weak: ['Agree', 'Disagree', 'Neutral']
stereotype_women_better_housekeepers: ['Agree', 'Disagree', 'Neutral']
stereotype_gentle_men_less_masculine: ['Agree', 'Disagree', 'Neutral']
childcare_only_mother_responsibility: ['No', 'Yes']
woman_home_man_provider_role: ['No', 'Yes']
chores_divided_equally_if_both_work: ['No, the woman should manage both', 'Yes, definitely']
support_equal_pay: ['No', 'Yes']
support_gender_diversity_quotas: ['No', 'Unsure', 'Yes']
discrimination_observed_nearby: ['No', 'Unsure', 'Yes']
support_gender_neutral_language: ['Maybe', 'No', 'Yes']
encourage_girls_nontraditional_careers: ['Maybe', 'No', 'Yes']
man_should_have_final_say_home: ['Maybe', 'No', 'Yes']
woman_should_not_tolerate_violence: ['Maybe', 'No', 'Yes']
sexist_jokes_okay: ['Maybe', 'No', 'Yes']
sensitization_reduces_gbv: ['Maybe', 'No', 'Yes']

## 7. Standardize Text Formatting
Even though this synthetic data was generated programmatically (and is therefore already fairly clean), we apply standard text-cleaning steps to demonstrate best practice and guard against stray whitespace or casing issues.

In [8]:
# Strip leading/trailing whitespace and standardize casing for all
# categorical (string) columns. This is a defensive step — even synthetic
# data benefits from this kind of standardization before analysis.
for col in categorical_cols:
    if df[col].dtype == object:
        df[col] = df[col].astype(str).str.strip()

print("Whitespace stripped from all text columns.")

Whitespace stripped from all text columns.

## 8. Convert Categorical Columns to pandas `category` dtype
Converting repetitive string columns to the `category` dtype reduces memory usage and makes downstream grouping/plotting operations faster and more explicit about the fact that these are categorical variables.

In [9]:
# Convert all categorical (non-ID) columns to pandas 'category' dtype
for col in categorical_cols:
    df[col] = df[col].astype('category')

# Confirm the dtype conversion
print(df.dtypes)

respondent_id                                   str
age_group                                  category
gender                                     category
education                                  category
heard_term_gender_sensitization            category
gender_is_binary_or_nonbinary              category
received_gender_training                   category
support_school_curriculum                  category
support_workplace_training                 category
sensitization_helps_relationships          category
stereotype_men_rational_women_emotional    category
stereotype_women_bad_drivers               category
view_okay_for_men_to_cry                   category
stereotype_men_strong_women_weak           category
stereotype_women_better_housekeepers       category
stereotype_gentle_men_less_masculine       category
childcare_only_mother_responsibility       category
woman_home_man_provider_role               category
chores_divided_equally_if_both_work        category
support_equal_pay                          category
support_gender_diversity_quotas            category
discrimination_observed_nearby             category
support_gender_neutral_language            category
encourage_girls_nontraditional_careers     category
man_should_have_final_say_home             category
woman_should_not_tolerate_violence         category
sexist_jokes_okay                          category
sensitization_reduces_gbv                  category
dtype: object

## 9. Enforce a Logical Ordering for Ordinal Columns
Some columns (like `age_group` and `education`) have a natural order. We explicitly set this order so that future plots and tables display categories in a logical sequence rather than alphabetically.

In [10]:
# Define the logical order for age groups
age_order = ["Less than 18", "18-25", "26-35", "More than 35"]
df["age_group"] = pd.Categorical(df["age_group"], categories=age_order, ordered=True)

# Define the logical order for education levels
edu_order = [
    "High school or equivalent",
    "Bachelor's degree",
    "Master's degree",
    "Doctoral or post-doctoral degree",
]
df["education"] = pd.Categorical(df["education"], categories=edu_order, ordered=True)

print("Ordinal ordering applied to 'age_group' and 'education'.")
print("\nAge group categories (in order):", df["age_group"].cat.categories.tolist())
print("Education categories (in order):", df["education"].cat.categories.tolist())

Ordinal ordering applied to 'age_group' and 'education'.

Age group categories (in order): ['Less than 18', '18-25', '26-35', 'More than 35']
Education categories (in order): ['High school or equivalent', "Bachelor's degree", "Master's degree", 'Doctoral or post-doctoral degree']

## 10. Sanity-Check Value Ranges
We confirm that every Yes/No/Agree-type column only contains values from its expected set, with no stray or unexpected categories slipping through generation.

In [11]:
# Define the expected value set per column for a final validation pass
expected_values = {
    "gender": {"Male", "Female"},
    "heard_term_gender_sensitization": {"Yes", "No"},
    "gender_is_binary_or_nonbinary": {"Binary", "Non-binary", "Unsure"},
    "received_gender_training": {"Yes", "No"},
    "support_school_curriculum": {"Yes, definitely", "Maybe", "No, not required"},
    "support_workplace_training": {"Yes, definitely", "Maybe", "No, not required"},
    "sensitization_helps_relationships": {"Yes", "Maybe", "No"},
    "chores_divided_equally_if_both_work": {
        "Yes, definitely", "No, the woman should manage both"
    },
    "support_equal_pay": {"Yes", "No"},
}

# Validate each column against its expected value set
all_valid = True
for col, expected_set in expected_values.items():
    actual_set = set(df[col].dropna().astype(str).unique())
    unexpected = actual_set - expected_set
    if unexpected:
        all_valid = False
        print(f"⚠ Unexpected values in '{col}': {unexpected}")

if all_valid:
    print("All checked columns contain only expected category values.")

All checked columns contain only expected category values.

## 11. Final Cleaned Dataset Overview
A final look at the cleaned, validated, type-corrected dataset before saving it for use in the EDA and Statistical Analysis notebooks.

In [12]:
# Final shape and dtype summary after cleaning
print(f"Final cleaned dataset shape: {df.shape[0]} rows x {df.shape[1]} columns")
print("\nData types after cleaning:")
print(df.dtypes)

df.head()

Final cleaned dataset shape: 1000 rows x 28 columns

Data types after cleaning:
respondent_id                                   str
age_group                                  category
gender                                     category
education                                  category
heard_term_gender_sensitization            category
gender_is_binary_or_nonbinary              category
received_gender_training                   category
support_school_curriculum                  category
support_workplace_training                 category
sensitization_helps_relationships          category
stereotype_men_rational_women_emotional    category
stereotype_women_bad_drivers               category
view_okay_for_men_to_cry                   category
stereotype_men_strong_women_weak           category
stereotype_women_better_housekeepers       category
stereotype_gentle_men_less_masculine       category
childcare_only_mother_responsibility       category
woman_home_man_provider_role               category
chores_divided_equally_if_both_work        category
support_equal_pay                          category
support_gender_diversity_quotas            category
discrimination_observed_nearby             category
support_gender_neutral_language            category
encourage_girls_nontraditional_careers     category
man_should_have_final_say_home             category
woman_should_not_tolerate_violence         category
sexist_jokes_okay                          category
sensitization_reduces_gbv                  category
dtype: object

,respondent_id,age_group,gender,education,heard_term_gender_sensitization,gender_is_binary_or_nonbinary,received_gender_training,support_school_curriculum,support_workplace_training,sensitization_helps_relationships,stereotype_men_rational_women_emotional,stereotype_women_bad_drivers,view_okay_for_men_to_cry,stereotype_men_strong_women_weak,stereotype_women_better_housekeepers,stereotype_gentle_men_less_masculine,childcare_only_mother_responsibility,woman_home_man_provider_role,chores_divided_equally_if_both_work,support_equal_pay,support_gender_diversity_quotas,discrimination_observed_nearby,support_gender_neutral_language,encourage_girls_nontraditional_careers,man_should_have_final_say_home,woman_should_not_tolerate_violence,sexist_jokes_okay,sensitization_reduces_gbv
0,R0001,18-25,Female,Bachelor's degree,Yes,Non-binary,No,Maybe,"Yes, definitely",Yes,Agree,Disagree,Agree,Agree,Agree,Disagree,No,Yes,"Yes, definitely",Yes,Yes,No,Maybe,Yes,No,Maybe,No,Yes
1,R0002,18-25,Male,Bachelor's degree,No,Non-binary,No,"No, not required","Yes, definitely",Yes,Disagree,Disagree,Agree,Disagree,Disagree,Agree,Yes,Yes,"Yes, definitely",Yes,Yes,Yes,Yes,Yes,No,No,No,Maybe
2,R0003,18-25,Female,Bachelor's degree,Yes,Binary,Yes,"No, not required","Yes, definitely",Yes,Disagree,Neutral,Agree,Disagree,Agree,Disagree,No,Yes,"No, the woman should manage both",Yes,Yes,No,Yes,Maybe,No,No,No,Yes
3,R0004,18-25,Male,Master's degree,Yes,Binary,No,"Yes, definitely","Yes, definitely",Yes,Agree,Disagree,Agree,Disagree,Agree,Disagree,No,No,"No, the woman should manage both",Yes,Yes,No,Yes,Yes,No,No,No,Yes
4,R0005,26-35,Male,Master's degree,Yes,Non-binary,Yes,Maybe,Maybe,Yes,Disagree,Disagree,Agree,Disagree,Disagree,Disagree,No,Yes,"Yes, definitely",Yes,Unsure,Unsure,Maybe,Yes,No,Yes,Maybe,Yes

## 12. Save the Cleaned Dataset
We save the cleaned DataFrame to `synthetic_survey_cleaned.csv` so it can be reused directly in `EDA.ipynb` and `Statistical_Analysis.ipynb` without repeating the cleaning steps.

In [13]:
# Save the cleaned dataset to a new CSV file
df.to_csv("synthetic_survey_cleaned.csv", index=False)
print("Cleaned dataset saved to 'synthetic_survey_cleaned.csv'.")
print("\nReminder: this remains a SYNTHETIC dataset, used only for demonstration purposes.")

Cleaned dataset saved to 'synthetic_survey_cleaned.csv'.

Reminder: this remains a SYNTHETIC dataset, used only for demonstration purposes.

## Summary

In this notebook we:
1. Loaded the synthetic survey dataset (1000 rows, 28 columns).
2. Inspected structure, data types, and column names.
3. Checked for (and confirmed the absence of) missing values and duplicates.
4. Validated categorical value sets.
5. Standardized text formatting and converted columns to appropriate `category` dtypes, including ordered categories for age and education.
6. Saved a cleaned version of the dataset for downstream analysis.

**Reminder: all data used and produced in this notebook is synthetic and fictional, generated for demonstration purposes only.**